analyze:
  v1:
    - name: processes.configmanagement.puppet
      labels:
        iconKey: puppet_logo
      registerVariables:
        - fileMatch:
            paths:
              - default/commands/ps/stdout
            regexpCapture:
              regexp: '.+puppet agent .*'
              index: 0
          name: ps
      condition:
        regexpMatch:
          regexp: 'puppet agent '
        variableRef: ps
      messages:
        conditionTrue:
          primary: Managed By Puppet
          detail: This server is running a Puppet agent
          severity: info
        conditionFalse:
          primary: No Puppet
          detail: This server is not running a puppet agent
          severity: debug
    - name: processes.configmanagement.chef
      labels:
        iconKey: chef_logo
      registerVariables:
      - fileMatch:
          paths:
            - default/commands/ps/stdout
          regexpCapture:
            regexp: '.+chef-client.*'
            index: 0
        name: ps
      condition:
        regexpMatch:
          regexp: 'chef-client'
        variableRef: ps
      messages:
        conditionTrue:
          primary: Managed By Chef
          detail: This server is running a Chef client
          severity: info
        conditionFalse:
          primary: No Chef
          detail: This server is not running a Chef client
          severity: debug
