analyze:
  v1:
    - name: processes.configmanagement.puppet
      labels:
        iconKey: puppet_logo
        desiredPosition: "10"
      insight:
        primary: Managed By Puppet
        detail: This server is running a Puppet agent
        severity: info
      registerVariables:
        - name: ps
          fileMatch:
            pathRegexps:
              - default/commands/ps/stdout
            regexpCapture:
              regexp: '.+puppet agent .*'
              index: 0
      evaluateConditions:
        - condition:
            regexpMatch:
              regexp: 'puppet agent '
            variableRef: ps
          insightOnFalse:
            primary: No Puppet
            detail: This server is not running a puppet agent
            severity: debug
            labels:
              iconKey: gray_checkmark
    - name: processes.configmanagement.chef
      labels:
        iconKey: chef_logo
        desiredPosition: "10"
      insight:
        primary: Managed By Chef
        detail: This server is running a Chef client
        severity: info
      registerVariables:
        - name: ps
          fileMatch:
            pathRegexps:
              - default/commands/ps/stdout
            regexpCapture:
              regexp: '.+chef-client.*'
              index: 0
      evaluateConditions:
        - condition:
            regexpMatch:
              regexp: 'chef-client'
            variableRef: ps
          insightOnFalse:
            primary: No Chef
            detail: This server is not running a Chef client
            severity: debug
            labels:
              iconKey: gray_checkmark
