project_name: support-bundle
release:
  github:
    owner: replicatedcom
    name: support-bundle
builds:
  - goos:
      - linux
    goarch:
      - amd64
      - "386"
    env:
      - CGO_ENABLED=0
    main: cmd/analyze/main.go
    ldflags: -s -w
      -X github.com/replicatedcom/support-bundle/pkg/version.version={{.Version}}
      -X github.com/replicatedcom/support-bundle/pkg/version.gitSHA={{.Commit}}
      -X github.com/replicatedcom/support-bundle/pkg/version.buildTime={{.Date}}
      -extldflags "-static"
    flags: -tags netgo -installsuffix netgo
    binary: analyze
    hooks: {}
  - goos:
      - linux
    goarch:
      - amd64
      - "386"
    main: cmd/support-bundle/main.go
    ldflags: -s -w
      -X github.com/replicatedcom/support-bundle/pkg/version.version={{.Version}}
      -X github.com/replicatedcom/support-bundle/pkg/version.gitSHA={{.Commit}}
      -X github.com/replicatedcom/support-bundle/pkg/version.buildTime={{.Date}}
    binary: support-bundle
    hooks: {}
archive:
  format: tar.gz
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}'
  files:
    - licence*
    - LICENCE*
    - license*
    - LICENSE*
    - readme*
    - README*
    - changelog*
    - CHANGELOG*
dockers:
  - image_templates:
      - replicated/analyze:latest
      - replicated/analyze:{{ .Major }}
      - replicated/analyze:{{ .Major }}.{{ .Minor }}
      - replicated/analyze:{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    dockerfile: deploy/Dockerfile-analyze
    goos: linux
    goarch: amd64
    binaries:
      - analyze
  - image_templates:
      - registry.replicated.com/library/support-bundle:latest
      - registry.replicated.com/library/support-bundle:{{ .Major }}
      - registry.replicated.com/library/support-bundle:{{ .Major }}.{{ .Minor }}
      - registry.replicated.com/library/support-bundle:{{ .Major }}.{{ .Minor }}.{{ .Patch }}
      - replicated/support-bundle:latest
      - replicated/support-bundle:{{ .Major }}
      - replicated/support-bundle:{{ .Major }}.{{ .Minor }}
      - replicated/support-bundle:{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    dockerfile: deploy/Dockerfile-collect
    goos: linux
    goarch: amd64
    binaries:
      - support-bundle
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
