project_name: support-bundle
release:
  github:
    owner: replicatedcom
    name: support-bundle
builds:
  - id: analyze
    goos:
      - linux
    goarch:
      - amd64
      - "386"
    env:
      - CGO_ENABLED=0
    main: cmd/analyze/main.go
    ldflags: -s -w
      -X github.com/replicatedcom/support-bundle/pkg/version.version={{.Version}}
      -X github.com/replicatedcom/support-bundle/pkg/version.gitSHA={{.Commit}}
      -X github.com/replicatedcom/support-bundle/pkg/version.buildTime={{.Date}}
      -extldflags "-static"
    flags: -tags netgo -installsuffix netgo
    binary: analyze
    hooks: {}
  - id: support-bundle
    goos:
      - linux
    goarch:
      - amd64
      - "386"
    main: cmd/support-bundle/main.go
    ldflags: -s -w
      -X github.com/replicatedcom/support-bundle/pkg/version.version={{.Version}}
      -X github.com/replicatedcom/support-bundle/pkg/version.gitSHA={{.Commit}}
      -X github.com/replicatedcom/support-bundle/pkg/version.buildTime={{.Date}}
    binary: support-bundle
    hooks: {}
archives:
- format: tar.gz
  files:
    - licence*
    - LICENCE*
    - license*
    - LICENSE*
    - readme*
    - README*
    - changelog*
    - CHANGELOG*
dockers:
  - image_templates:
      - replicated/analyze:alpha
    dockerfile: deploy/Dockerfile-analyze
    goos: linux
    goarch: amd64
    binaries:
      - analyze
  - image_templates:
      - replicated/support-bundle:alpha
    dockerfile: deploy/Dockerfile-collect
    goos: linux
    goarch: amd64
    binaries:
      - support-bundle
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
