FROM debian:9
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install --no-install-recommends -y \
    ca-certificates \
  && rm -rf /var/lib/apt/lists/*
COPY support-bundle /usr/local/bin/support-bundle
ENTRYPOINT [ "support-bundle" ]
CMD [ "generate" ]
