FROM debian:stretch-slim
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install --no-install-recommends -y \
    ca-certificates \
    curl \
    iproute2 \
    procps \
    systemd \
    jq \
    \
    \
  && apt-get upgrade -y perl-base gnupg gpgv libssl1.0.2 \
  && rm -rf /var/lib/apt/lists/* \
  && update-ca-certificates
RUN export CLOUD_SDK_REPO="cloud-sdk-stretch" && \
  echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
  curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
  DEBIAN_FRONTEND=noninteractive apt-get update -y && apt-get install google-cloud-sdk -y --no-install-recommends && \
  rm -rf /var/lib/apt/lists/*
