FROM debian:stretch-slim
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install --no-install-recommends -y \
    ca-certificates \
    iproute2 \
    procps \
    systemd \
    \
    \
  && apt-get upgrade -y perl-base gnupg gpgv \
  && rm -rf /var/lib/apt/lists/* \
  && update-ca-certificates
COPY support-bundle /usr/local/bin/support-bundle

ENV IN_CONTAINER 1
LABEL "com.replicated.support-bundle"="true"
ENTRYPOINT [ "support-bundle" ]
CMD [ "generate" ]
