FROM debian:buster-slim
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && apt-get install --no-install-recommends -y \
    ca-certificates \
    curl \
    iproute2 \
    procps \
    systemd \
    jq \
    gnupg \
    \
    \
    libp11-kit0 \
  && apt-get clean \
  && apt-get autoremove -y \
  && rm -rf /var/lib/apt/lists/* \
  && update-ca-certificates
RUN export CLOUD_SDK_REPO="cloud-sdk-stretch" \
  && echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \
  && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - \
  && apt-get update -y && apt-get install --no-install-recommends -y \
    google-cloud-sdk \
  && apt-get clean \
  && apt-get autoremove -y \
  && rm -rf /var/lib/apt/lists/* \
  && update-ca-certificates
WORKDIR /out
