FROM replicated/support-bundle:base

COPY support-bundle /usr/local/bin/support-bundle

ENV IN_CONTAINER 1
LABEL "com.replicated.support-bundle"="true"
ENTRYPOINT [ "support-bundle" ]
CMD [ "generate" ]
