FROM debian:bookworm-slim
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && apt-get install --no-install-recommends -y \
    ca-certificates \
    curl \
    iproute2 \
    procps \
    systemd \
    jq \
    gnupg \
    openssl \
    \
    \
  && apt-get clean \
  && apt-get autoremove -y \
  && rm -rf /var/lib/apt/lists/* \
  && update-ca-certificates

WORKDIR /out
