FROM replicated/support-bundle:base

COPY analyze /usr/local/bin/analyze

ENV IN_CONTAINER 1
LABEL "com.replicated.support-bundle"="true"
LABEL "com.replicated.analyze"="true"
ENTRYPOINT [ "analyze" ]
