FROM alpine:latest
RUN apk add --no-cache \
    ca-certificates \
    jq \
  && update-ca-certificates
COPY analyze /analyze

ENV IN_CONTAINER 1
LABEL "com.replicated.analyze"="true"
WORKDIR /out
ENTRYPOINT [ "/analyze" ]
