// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/replicatedcom/support-bundle/pkg/collect/bundle/reader (interfaces: BundleReader)

// Package reader is a generated GoMock package.
package reader

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	reader "github.com/replicatedcom/support-bundle/pkg/collect/bundle/reader"
	types "github.com/replicatedcom/support-bundle/pkg/collect/types"
)

// MockBundleReader is a mock of BundleReader interface
type MockBundleReader struct {
	ctrl     *gomock.Controller
	recorder *MockBundleReaderMockRecorder
}

// MockBundleReaderMockRecorder is the mock recorder for MockBundleReader
type MockBundleReaderMockRecorder struct {
	mock *MockBundleReader
}

// NewMockBundleReader creates a new mock instance
func NewMockBundleReader(ctrl *gomock.Controller) *MockBundleReader {
	mock := &MockBundleReader{ctrl: ctrl}
	mock.recorder = &MockBundleReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBundleReader) EXPECT() *MockBundleReaderMockRecorder {
	return m.recorder
}

// GetErrorIndex mocks base method
func (m *MockBundleReader) GetErrorIndex() []types.Result {
	ret := m.ctrl.Call(m, "GetErrorIndex")
	ret0, _ := ret[0].([]types.Result)
	return ret0
}

// GetErrorIndex indicates an expected call of GetErrorIndex
func (mr *MockBundleReaderMockRecorder) GetErrorIndex() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetErrorIndex", reflect.TypeOf((*MockBundleReader)(nil).GetErrorIndex))
}

// GetIndex mocks base method
func (m *MockBundleReader) GetIndex() []types.Result {
	ret := m.ctrl.Call(m, "GetIndex")
	ret0, _ := ret[0].([]types.Result)
	return ret0
}

// GetIndex indicates an expected call of GetIndex
func (mr *MockBundleReaderMockRecorder) GetIndex() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndex", reflect.TypeOf((*MockBundleReader)(nil).GetIndex))
}

// NewScanner mocks base method
func (m *MockBundleReader) NewScanner() (reader.Scanner, error) {
	ret := m.ctrl.Call(m, "NewScanner")
	ret0, _ := ret[0].(reader.Scanner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewScanner indicates an expected call of NewScanner
func (mr *MockBundleReaderMockRecorder) NewScanner() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewScanner", reflect.TypeOf((*MockBundleReader)(nil).NewScanner))
}
