ignore:
  # https://github.com/anchore/grype#specifying-matches-to-ignore
  # example to ignore a vulnerability
  # This is the full set of supported rule fields:
  # - vulnerability: CVE-2008-4318
  #   fix-state: unknown
  #   package:
  #     name: libcurl
  #     version: 1.5.1
  #     type: npm
  #     location: "/usr/local/lib/node_modules/**"

- package:
    type: go-module

# google-cloud-sdk python vulns
- vulnerability: GHSA-w7pp-m8wf-vj6r
  package:
    name: cryptography
    version: 36.0.2
    type: python
    location: "/usr/lib/google-cloud-sdk/platform/bundledpythonunix/lib/**"
- vulnerability: GHSA-x4qr-2fvf-3mr5
  package:
    name: cryptography
    version: 36.0.2
    type: python
    location: "/usr/lib/google-cloud-sdk/platform/bundledpythonunix/lib/**"
- vulnerability: GHSA-vvpx-j8f3-3w6h
  package:
    name: golang.org/x/net
    version: v0.5.0
    type: go-module
    location: "/usr/lib/google-cloud-sdk/bin/**"
