ignore:
  - vulnerability: CVE-2023-47038
  - vulnerability: CVE-2023-5981

  # https://github.com/anchore/grype#specifying-matches-to-ignore
  # example to ignore a vulnerability
  # This is the full set of supported rule fields:
  # - vulnerability: CVE-2008-4318
  #   fix-state: unknown
  #   package:
  #     name: libcurl
  #     version: 1.5.1
  #     type: npm
  #     location: "/usr/local/lib/node_modules/**"

  - package:
      type: go-module

  # google-cloud-sdk python vulns
  - vulnerability: GHSA-jfhm-5ghh-2f97
    package:
      name: cryptography
      version: 41.0.5
      type: python
      location: "/usr/lib/google-cloud-sdk/platform/bundledpythonunix/lib/**"
  - vulnerability: GHSA-mq26-g339-26xf
    package:
      name: pip
      version: 23.2.1
      type: python
      location: "/usr/lib/google-cloud-sdk/platform/bundledpythonunix/lib/**"
